### PR TITLE
Add inventory toggle

### PR DESCRIPTION
**Pull request by Lanselotto**

### CODE REVIEW

**Comment by LeonBlade** [comment]
Thanks, I'll take a look at this soon.

**Comment by LeonBlade** [comment]
I have changed the way that visible is done, but I have made the adjustments needed on my end for this.

**Comment by Lanselotto** [comment]
oh, I didn't know exactly what they were for and they seemed to have no effect without the grid so I didn't hide them.

**Comment by LeonBlade** [comment]
If you're on the key items and crystals section they show up. I went ahead and added all the appropriate addons in my local branch. If you can just answer the other comments I'll push this through to the repo.

**Pull request merged**
